{{- if (and (or (.Values.scalyr.k8s.enableMetrics) (.Values.scalyr.k8s.enableLogs)) .Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-sa
  labels:
    {{- include "scalyr-helm.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
secrets:
  - name: "scalyr-api-key"
automountServiceAccountToken: true
{{- end }}
